/*
# This file is autogenerated
# You can modify.
*/

#include "din0_sequence.hpp"


using din0_sequence_packet = dti_packet<queue_type<sc_dt::sc_uint<8>, 1> >;
template class din0_sequence<din0_sequence_packet, din0_sequence_packet >;


template <typename packet_type,typename RSP>
void din0_sequence<packet_type, RSP>::gen_seq(){
  for (int i=0; i<10; i++){
    data.push_back(i);
  }

}
