/*
# This file is autogenerated
# You can modify.
*/

#include "din1_sequence.hpp"


using din1_sequence_packet = dti_packet<queue_type<sc_dt::sc_uint<8>, 1> >;
template class din1_sequence<din1_sequence_packet, din1_sequence_packet >;


template <typename packet_type,typename RSP>
void din1_sequence<packet_type, RSP>::gen_seq(){
  for (int i=0; i<10; i++){
    data.push_back(i);
  }
}
