/*
# This file is autogenerated
# You can modify.
*/

#include "phase_sequence.hpp"
#include <cmath>
#include <scv.h>
#include <iostream>

#define PHASE_TR_NUM 100000

using phase_sequence_packet = dti_packet<integer_type<sc_dt::sc_uint<16>>>;
template class phase_sequence<phase_sequence_packet, phase_sequence_packet>;

template <typename packet_type, typename RSP>
void phase_sequence<packet_type, RSP>::gen_seq() {
  unsigned int pi = pow(2, 16) / 2;

  scv_smart_ptr<float> phase_ang ("phase_ang");
  phase_ang->keep_only(0, 2*M_PI);

  for(int j = 0; j < PHASE_TR_NUM; j++){
    phase_ang->next();
    this->phase_cg.sample(*phase_ang);
    data.push_back(pi * (*phase_ang));
  }
}
