/*
# This file is autogenerated
# You can modify.
*/

#include "phase_sequence.hpp"

using phase_sequence_packet = dti_packet<integer_type<sc_dt::sc_uint<16>>>;
template class phase_sequence<phase_sequence_packet, phase_sequence_packet>;

template <typename packet_type, typename RSP>
void phase_sequence<packet_type, RSP>::gen_seq() {
  for (int i = 0; i < 65535; i++) {
    data.push_back(i);
  }
}
